export type DriverStatus = "Ativo" | "Inativo";

export type DriverCard = {
  id: string;
  name: string;
  initials: string;
  verified: boolean;
  status: DriverStatus;
  email: string;
  phone: string;
  vehicle: string;
  rating: string;
  rides: number;
  /** Parte numérica para exibir "Kz X Ganhos" */
  earningsKz: string;
  avatarClass: string;
};

export const DRIVERS_SUMMARY = {
  total: 420,
  active: 300,
  activeTrend: "+2.1%",
  inactive: 45,
  avgRating: "4.72",
};

export const DRIVERS_MOCK: DriverCard[] = [
  {
    id: "M008",
    name: "Tiago Silva",
    initials: "TS",
    verified: true,
    status: "Ativo",
    email: "tiago.silva@email.com",
    phone: "+244 923 456 789",
    vehicle: "Cinza. Suzuki S-Presso - LDA-23-92-AC",
    rating: "5.0",
    rides: 654,
    earningsKz: "150.000",
    avatarClass: "bg-pika-primary text-white",
  },
  {
    id: "M014",
    name: "Carla Mendes",
    initials: "CM",
    verified: true,
    status: "Ativo",
    email: "carla.mendes@email.com",
    phone: "+244 924 112 003",
    vehicle: "Branco. Toyota Corolla - LD-19-88-BQ",
    rating: "4.9",
    rides: 512,
    earningsKz: "128.500",
    avatarClass: "bg-sky-600 text-white",
  },
  {
    id: "M021",
    name: "Paulo Kassoma",
    initials: "PK",
    verified: false,
    status: "Inativo",
    email: "paulo.kassoma@email.com",
    phone: "+244 931 009 441",
    vehicle: "Prata. Hyundai i10 - LDB-02-33-JX",
    rating: "4.6",
    rides: 198,
    earningsKz: "42.300",
    avatarClass: "bg-slate-500 text-white",
  },
  {
    id: "M003",
    name: "Ana Rodrigues",
    initials: "AR",
    verified: true,
    status: "Ativo",
    email: "ana.rodrigues@email.com",
    phone: "+244 926 778 120",
    vehicle: "Preto. Nissan Almera - LD-55-01-AA",
    rating: "4.8",
    rides: 421,
    earningsKz: "98.750",
    avatarClass: "bg-emerald-600 text-white",
  },
  {
    id: "M031",
    name: "Miguel Tchimbundo",
    initials: "MT",
    verified: true,
    status: "Ativo",
    email: "miguel.t@email.com",
    phone: "+244 933 221 884",
    vehicle: "Azul. Honda Fit - LD-11-44-CC",
    rating: "5.0",
    rides: 702,
    earningsKz: "168.200",
    avatarClass: "bg-indigo-600 text-white",
  },
  {
    id: "M012",
    name: "Helena Costa",
    initials: "HC",
    verified: true,
    status: "Inativo",
    email: "helena.costa@email.com",
    phone: "+244 925 667 332",
    vehicle: "Vermelho. Kia Picanto - LDA-90-12-EF",
    rating: "4.7",
    rides: 305,
    earningsKz: "76.000",
    avatarClass: "bg-rose-500 text-white",
  },
  {
    id: "M019",
    name: "Bruno Agostinho",
    initials: "BA",
    verified: false,
    status: "Ativo",
    email: "bruno.agostinho@email.com",
    phone: "+244 922 334 551",
    vehicle: "Cinza. Volkswagen Polo - LD-08-77-GH",
    rating: "4.5",
    rides: 289,
    earningsKz: "61.400",
    avatarClass: "bg-amber-600 text-white",
  },
  {
    id: "M027",
    name: "Sónia Manuel",
    initials: "SM",
    verified: true,
    status: "Ativo",
    email: "sonia.manuel@email.com",
    phone: "+244 930 888 019",
    vehicle: "Branco. Toyota Yaris - LDB-45-66-KL",
    rating: "4.9",
    rides: 540,
    earningsKz: "132.000",
    avatarClass: "bg-teal-600 text-white",
  },
  {
    id: "M005",
    name: "Ricardo Barros",
    initials: "RB",
    verified: true,
    status: "Ativo",
    email: "ricardo.barros@email.com",
    phone: "+244 927 001 772",
    vehicle: "Preto. Mercedes C180 - LD-33-22-MN",
    rating: "4.8",
    rides: 388,
    earningsKz: "112.900",
    avatarClass: "bg-zinc-700 text-white",
  },
  {
    id: "M016",
    name: "João Fernandes",
    initials: "JF",
    verified: true,
    status: "Inativo",
    email: "joao.fernandes@email.com",
    phone: "+244 928 445 009",
    vehicle: "Prata. Renault Logan - LDA-77-55-OP",
    rating: "4.4",
    rides: 176,
    earningsKz: "38.200",
    avatarClass: "bg-blue-700 text-white",
  },
  {
    id: "M022",
    name: "Patrícia Nunes",
    initials: "PN",
    verified: true,
    status: "Ativo",
    email: "patricia.nunes@email.com",
    phone: "+244 934 120 663",
    vehicle: "Branco. Suzuki Swift - LD-66-11-QR",
    rating: "5.0",
    rides: 612,
    earningsKz: "145.800",
    avatarClass: "bg-fuchsia-600 text-white",
  },
  {
    id: "M009",
    name: "Nelson Tati",
    initials: "NT",
    verified: false,
    status: "Ativo",
    email: "nelson.tati@email.com",
    phone: "+244 921 998 004",
    vehicle: "Cinza. Dacia Sandero - LDB-14-28-ST",
    rating: "4.6",
    rides: 334,
    earningsKz: "72.650",
    avatarClass: "bg-cyan-700 text-white",
  },
];
